# Generated by Django 4.1.2 on 2022-10-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rules",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created Timestamp",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Updated Timestamp",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="is active", verbose_name="Is active"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.JSONField(
                        help_text="Name of the rule in JSON", verbose_name="Rule Name"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
