# Generated by Django 4.1.2 on 2022-10-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rules",
            name="name",
            field=models.JSONField(
                help_text="Name of the rule(JSON)", verbose_name="Rule Name"
            ),
        ),
    ]
