# Generated by Django 4.1.2 on 2022-10-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_alter_rules_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rules",
            options={"ordering": ["-id"]},
        ),
    ]
