# Generated by Django 4.1.2 on 2022-10-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_alter_rules_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rules",
            options={"ordering": ["-id"], "verbose_name_plural": "Rules"},
        ),
    ]
