# Generated by Django 4.1.2 on 2022-10-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0004_alter_rules_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rules",
            new_name="Rule",
        ),
    ]
