# Generated by Django 4.1.2 on 2022-11-01 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0009_alter_rule_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTracker",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created Timestamp",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Updated Timestamp",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="is active", verbose_name="Is active"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.BooleanField(verbose_name="Completed")),
                (
                    "rule_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.rule",
                        verbose_name="rule id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
