# Generated by Django 4.1.2 on 2022-11-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0011_dailytracker_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytracker",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Date"),
        ),
    ]
