# Generated by Django 4.1.2 on 2022-11-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0012_alter_dailytracker_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailytracker",
            options={"ordering": ["-id"], "verbose_name_plural": "DailyTrackers"},
        ),
        migrations.AlterUniqueTogether(
            name="dailytracker",
            unique_together={("date", "rule_id")},
        ),
    ]
