# Generated by Django 4.1.2 on 2022-11-02 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0014_alter_dailytracker_rule_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytracker",
            name="rule_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="health.rule",
                verbose_name="rule id",
            ),
        ),
    ]
