# Generated by Django 4.1.2 on 2022-11-02 21:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0015_alter_dailytracker_rule_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytracker",
            name="date",
            field=models.DateField(
                default=datetime.date(2022, 11, 2), verbose_name="Date"
            ),
        ),
    ]
