# Generated by Django 4.1.2 on 2022-11-02 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0016_alter_dailytracker_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytracker",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Date"
            ),
        ),
    ]
