# Generated by Django 4.1.2 on 2022-11-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0018_alter_dailytracker_rule_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="name",
            field=models.CharField(
                help_text="Name of the rule", max_length=300, verbose_name="Rule Name"
            ),
        ),
    ]
