# Generated by Django 4.1.2 on 2022-10-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="address2",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="zip",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
