# Generated by Django 4.1.2 on 2022-11-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="education",
            field=models.JSONField(default={}, verbose_name="Education"),
        ),
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.TextField(default={}, verbose_name="Notes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.JSONField(default={}, verbose_name="Skills"),
        ),
    ]
