# Generated by Django 4.1.2 on 2022-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_user_education_user_notes_user_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audit",
            name="message",
        ),
        migrations.AddField(
            model_name="audit",
            name="task_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Task Id"),
        ),
    ]
