# Generated by Django 4.1.2 on 2022-11-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_remove_audit_message_audit_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[
                    ("ERROR", "ERROR"),
                    ("SUCCESS", "SUCCESS"),
                    ("IN_PROGRESS", "IN-PROGRESS"),
                    ("CREATED", "CREATED"),
                    ("COMPLETED", "COMPLETED"),
                    ("SKIPPED", "SKIPPED"),
                ],
                default="SKIPPED",
                max_length=15,
                verbose_name="Status",
            ),
            preserve_default=False,
        ),
    ]
