# Generated by Django 4.1.2 on 2022-11-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_audit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[
                    ("ERROR", "ERROR"),
                    ("SUCCESS", "SUCCESS"),
                    ("IN_PROGRESS", "IN-PROGRESS"),
                    ("CREATED", "CREATED"),
                    ("COMPLETED", "COMPLETED"),
                    ("SKIPPED", "SKIPPED"),
                    ("INFO", "INFO"),
                ],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="education",
            field=models.JSONField(default=dict, verbose_name="Education"),
        ),
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.JSONField(default=dict, verbose_name="Skills"),
        ),
    ]
