# Generated by Django 4.1.2 on 2022-11-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_audit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Task Id"
            ),
        ),
    ]
