# Generated by Django 4.1.2 on 2022-11-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_audit_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audit",
            options={"ordering": ["-id"], "verbose_name_plural": "Audit"},
        ),
    ]
