# Generated by Django 4.1.2 on 2022-12-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_actionlist_actionlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionlog",
            options={"ordering": ["id"]},
        ),
    ]
