# Generated by Django 4.1.2 on 2022-12-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_actionlist_delete_actionliststage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actionlist",
            old_name="task",
            new_name="action",
        ),
    ]
