# Generated by Django 4.1.2 on 2022-12-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_rename_task_actionlist_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionlist",
            options={"ordering": ["-name"]},
        ),
        migrations.AlterUniqueTogether(
            name="actionlist",
            unique_together={("name", "action")},
        ),
    ]
