# Generated by Django 4.1.2 on 2022-12-18 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_actionlog_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
