# Generated by Django 4.1.2 on 2022-11-07 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieflex", "0002_alter_media_options_alter_watching_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watching",
            name="current_watch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="movieflex.media",
                verbose_name="watch",
            ),
        ),
    ]
