# Generated by Django 4.1.2 on 2022-11-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieflex", "0005_alter_media_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="thumb_nail",
            field=models.ImageField(
                default="linux.jpg", upload_to="", verbose_name="default"
            ),
        ),
    ]
