# Generated by Django 4.1.4 on 2022-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created Timestamp', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated Timestamp', verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, help_text='is active', verbose_name='Is active')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project Name', max_length=50, verbose_name='Project Name')),
                ('project_id', models.IntegerField(help_text='Project id', verbose_name='Project id')),
                ('url', models.URLField(help_text='Git URL', max_length=300, verbose_name='Git URL')),
                ('git', models.CharField(choices=[('gitlab', 'Gitlab'), ('github', 'Github')], default='Github', help_text='Git', max_length=200, verbose_name='Git')),
                ('namespace', models.CharField(help_text='Namespace', max_length=50, verbose_name='Namespace')),
                ('default_branch', models.CharField(help_text='Default Branch', max_length=10, verbose_name='Default Branch')),
                ('ssh_url_to_repo', models.CharField(help_text='SSH url to repo', max_length=250, verbose_name='SSH url to repo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
