# Generated by Django 4.1.2 on 2022-10-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitsvn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdetail",
            name="git",
            field=models.CharField(
                choices=[("gitlab", "Gitlab"), ("github", "Github")],
                default="Github",
                help_text="Git",
                max_length=200,
                verbose_name="Git",
            ),
        ),
    ]
