# Generated by Django 4.1.2 on 2022-10-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitsvn", "0002_projectdetail_git"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdetail",
            name="default_branch",
            field=models.CharField(
                default="main",
                help_text="Default Branch",
                max_length=10,
                verbose_name="Default Branch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectdetail",
            name="namespace",
            field=models.CharField(
                default="mysubsnewslivecom/hello-two-u",
                help_text="Namespace",
                max_length=50,
                verbose_name="Namespace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectdetail",
            name="ssh_url_to_repo",
            field=models.CharField(
                default="git@gitlab.com",
                help_text="SSH url to repo",
                max_length=250,
                verbose_name="SSH url to repo",
            ),
            preserve_default=False,
        ),
    ]
