# Generated by Django 4.1.2 on 2022-11-07 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Name", max_length=250, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("TV", "TV"), ("MOVIE", "Movie"), ("ANIME", "Anime")],
                        max_length=250,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        choices=[
                            ("FANTASY", "Fantasy"),
                            ("ACTION", "Action"),
                            ("ADVENTURE", "Adventure"),
                        ],
                        max_length=250,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Watching",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("completed", models.BooleanField(default=True)),
                (
                    "current_watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="movflex.media",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
